---
abstract: 'Control how failed type constraint checks are handled'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Attribute-TypeConstraint-CustomizeFatal
no_index:
  directory:
    - t
requires:
  Carp: 0
  Moose::Role: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Try::Tiny: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Attribute-TypeConstraint-CustomizeFatal
  homepage: http://metacpan.org/release/MooseX-Attribute-TypeConstraint-CustomizeFatal
  license: http://dev.perl.org/licenses/
  repository: git://github.com/avar/moosex-attribute-typeconstraint-customizefatal.git
version: 0.01
x_authority: cpan:AVAR
